spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: tencent_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

        # product 微服务 /api/product/** -> /**
        - id: product_route
          uri: lb://cubemall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        # renren-fast 微服务 /api/** -> /renren-fast/**
        - id: admin_route
          uri: lb://renren-fast
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}