server:
  port: 8082

# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://47.113.81.149:3306/cube_goods?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://112.124.39.204:3306/cube_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  application:
      name: cubemall-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379

  session:
      store-type: redis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.kkb.cubemall: debug
# client_secret: d4660fb2c048b91b19bea755f79ca1e1e088b175
github:
  # 客户端ID
  clientId: dca9b7495f5d72401156
  # 客户端秘钥
  clientSecret: d4660fb2c048b91b19bea755f79ca1e1e088b175
  # 用户授权地址（返回授权码）
  authorizationUrl: https://github.com/login/oauth/authorize
  # 回调地址，获取access_token
  redirectUrl: http://localhost:8082/auth2/success
  # 认证服务器生成access_token
  accessTokenUrl: https://github.com/login/oauth/access_token
  # 获取用户身份信息
  userInfoUrl: https://api.github.com/user
